### ISSUE TITLE
安裝

### ISSUE THREAD

**Issue by ytc1012** [go-nunu/nunu#1]
windows安裝好以后，nunu new 失败：无法将“nunu”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。

**Comment by codingcn** [comment]
这是因为你的golang环境没有正常配置，可以把 GOBIN 目录配置到环境变量中即可

配置完GOBIN之后重新运行下`go install`，刚刚我更新了新代码

```
go install github.com/go-nunu/nunu@latest
```
