### ISSUE TITLE
框架有监控，链路追踪的技术方案吗？

### ISSUE THREAD

**Issue by huagelong** [go-nunu/nunu#12]
框架跟同类相比，非常不错！
不过看了文档，没有监控，链路追踪的方案。
监控，链路追踪是发现线上问题很重要的一环，本框架有技术方案可以提供吗？

**Comment by codingcn** [comment]
该项目目前定位于快速构建单体服务，而链路追踪多见于微服务项目，目前nunu只实现了log traceid记录。

监控的话，可以自己接入Prometheus、grafana、efk之类的，实现也比较简单。

如果大家有什么比较好的想法，欢迎PR，一起完善该项目哈

**Comment by huagelong** [comment]
https://github.com/apache/skywalking-go  目前我找到这个
