### ISSUE TITLE
测试文件调用路由的问题

### ISSUE THREAD

**Issue by Yuni7** [go-nunu/nunu#15]
![image](https://github.com/go-nunu/nunu/assets/97076016/a28f99ef-a110-415e-9e2e-4c450384bf50)
![image](https://github.com/go-nunu/nunu/assets/97076016/77caa46d-2444-453b-9dcb-6b0b1aeded69)

在新建了一个menusHandler的情况下。user_test 的setupRouter 里面 在使用到NewServerHTTP()的时候 也需要传入menusHandler。
我应该怎么改进它呢？

**Comment by codingcn** [comment]
我重新编写了下`heanlder`单测代码，具体可参考

https://github.com/go-nunu/nunu-layout-advanced/blob/main/test/server/handler/user_test.go
