### ISSUE TITLE
handler 使用接口 的目的是什么

### ISSUE THREAD

**Issue by ming200825** [go-nunu/nunu#19]

**Comment by codingcn** [comment]
golang的面向接口编程，可以查阅下单元测试部分的文档。

**Comment by codingcn** [comment]
`handler`相较于`service`和`repo`可以不使用interface，因为`handler`无需mock，可自行取舍哈

**Comment by zhangxiaohua1215** [comment]
希望可以在后续版本取消handler使用接口，感觉有点画蛇添足了，而且每写一个方法都要到interface中声明，不用interface完成可以省略这个步骤

**Comment by codingcn** [comment]
> 希望可以在后续版本取消handler使用接口，感觉有点画蛇添足了，而且每写一个方法都要到interface中声明，不用interface完成可以省略这个步骤

可以，下个版本移除

**Comment by zhangxiaohua1215** [comment]
> > 希望可以在后续版本取消handler使用接口，感觉有点画蛇添足了，而且每写一个方法都要到interface中声明，不用interface完成可以省略这个步骤
> 
> 可以，下个版本移除

感谢采纳🌹

**Comment by codingcn** [comment]
handler接口已移除

https://github.com/go-nunu/nunu-layout-advanced/commit/55b0cbdc6a85455a171622b2ac73a5ca59156632
