### ISSUE TITLE
build and run error

### ISSUE THREAD

**Issue by zq201811** [go-nunu/nunu#2]
nunu run :
package demo/cmd/server
imports demo/pkg/config: build constraints exclude all Go files in x:\work\code\go\demo\pkg\config

go build :
package demo/cmd/server
imports demo/pkg/config: build constraints exclude all Go files in x:\work\code\go\demo\pkg\config

runtime: go 1.20

**Comment by codingcn** [comment]
Thank you for feedback. The issue has been successfully fixed. Please delete the old project first and try running 'nunu new' again`.

**Comment by zq201811** [comment]
> Thank you for feedback. The issue has been successfully fixed. Please delete the old project first and try running `nunu new` again.

老铁 666
