### ISSUE TITLE
部署生产环境是打包还是通过git拉取代码直接run呢？

### ISSUE THREAD

**Issue by mme1** [go-nunu/nunu#28]
比如job服务，如果有很多定时任务，打包的话，是不是要先停了原来的服务，在把新包传上去再开启呢。
还是说每一个定时任务，都要单独打包呢？

**Comment by codingcn** [comment]
通常来说，生产环境一定是`go build`之后运行，`go run`或者`nunu run`仅用作本地开发使用。

job服务的话，可以手动关闭旧服务，再启动新服务。

其次可以基于`k8s`或`swarm`实现go服务的滚动更新，具体流程可以网上搜下。

**Comment by mme1** [comment]
job服务如果手动关闭旧服务，会不会正在执行的任务就断了呢？这个该如何避免呢。

**Comment by codingcn** [comment]
job 服务比较特殊，对于长任务，需要自己在代码层处理任务的幂等以及中断等逻辑。

**Comment by mme1** [comment]
okk
