### ISSUE TITLE
windows 上每次更新文件都会弹出防火墙警告

### ISSUE THREAD

**Issue by xqa** [go-nunu/nunu#30]
如题，每次都点允许很烦，而且防火墙允许的应用会多出非常多无用选项
![image](https://github.com/go-nunu/nunu/assets/107579458/5a96daa8-8e12-4083-a84c-f411528a9605)

我查了下需要在启动端口前面加上127.0.0.1。如果说本地开发调试我感觉这样会好一点，`":%d"`在部署的时候用
```go
http.Run(servers.ServerHTTP, fmt.Sprintf(":%d", conf.GetInt("http.port")))
改成
http.Run(servers.ServerHTTP, fmt.Sprintf("127.0.0.1:%d", conf.GetInt("http.port")))
```
还有种方案就是添加入站规则方向项目运行的端口。

你有啥想法和建议？

**Comment by codingcn** [comment]
没怎么用过windows。如果127.0.0.1不弹防火墙的话，那本地开发直接设置127.0.0.1没啥问题，个人改下就行哈

**Comment by xqa** [comment]
有计划把那个热更新改成air吗，不知道是不是错觉，本地运行的感觉用air要快些，而且资源占用没那么高，还能指定输出路径到当前项目（这样不会有防火墙警告，也不会在临时目录生成文件），可配置性要好些。我当前时这样改的，就给个建议 :smile:

**Comment by codingcn** [comment]
air 的代码实现其实和nunu run基本一样，如果需要配合使用air的话，也可以的。

**Comment by xqa** [comment]
我看了你的源码，你那相当于精简版，都差不多，就是没法配置。我自己改着用吧
