### ISSUE TITLE
使用gorm.gen 生成query代码的, 使用nunu run会监视文件改变不断地重复执行nunu run

### ISSUE THREAD

**Issue by Tooooommy** [go-nunu/nunu#32]
![image](https://github.com/go-nunu/nunu/assets/13863496/2f68e7de-ff83-416e-aa14-6165f684428a)
可以使用参数选择性启用文件监视吗？
nunu run -w xxxx.go

**Comment by codingcn** [comment]
v1.0.8版本已添加支持，请更新下nunu版本

```
 go install github.com/go-nunu/nunu@v1.0.8
```

命令示例

```
nunu run ./cmd/server  --excludeDir=".git,tmp,vendor" --includeExt="go,yml"  -- --conf=./config/local.yml
```

## 新特性说明：
* 支持过滤排除指定目录`excludeDir`
* 支持监听指定后缀文件类型`includeExt`
* 支持传递服务进程参数，`--`分隔符之后的参数为程序子进程参数
