### ISSUE TITLE
如何开启websocket服务

### ISSUE THREAD

**Issue by lantingx7** [go-nunu/nunu#33]

**Comment by codingcn** [comment]
GRPC以及WS的整合已经在开发了，过段时间会开源出来。

**Comment by lantingx7** [comment]
谢谢大佬

**Comment by hcclinux** [comment]
> GRPC以及WS的整合已经在开发了，过段时间会开源出来。

能否告知大概什么时候上线这个功能呢

**Comment by codingcn** [comment]
> > GRPC以及WS的整合已经在开发了，过段时间会开源出来。
> 
> 能否告知大概什么时候上线这个功能呢

这周末吧，最近工作比较忙

**Comment by AzraelJi** [comment]
开源了吗，好像没看到ws功能

**Comment by codingcn** [comment]
> 开源了吗，好像没看到ws功能

ws这个先delay了，工作太忙了，天天加班。

**Comment by lycheezhou** [comment]
怎么回事 加班有工资吗

**Comment by Wenrh2004** [comment]
我可以尝试为其添加ws支持嘛

**Comment by codingcn** [comment]
> 我可以尝试为其添加ws支持嘛

👏🏻欢迎PR

**Comment by codingcn** [comment]
Nunu关于Websocket/TCP的支持已经集成，欢迎体验~

创建项目命令

nunu new chat-demo -r https://gitee.com/go-nunu/nunu-layout-chat.git


运行项目
 cd chat-demo 

nunu run ./cmd/server


开启多个浏览器窗口，加入聊天室即可体验
http://127.0.0.1:8000/
