### ISSUE TITLE
新增加一个model后如何自动在数据库中创建相应的表？

### ISSUE THREAD

**Issue by lorenzohee** [go-nunu/nunu#36]
通过nunu create model role 后成功创建role的model，修改完role对应的属性后，如何在数据库中创建相应的表？

我当前的做法是在``/internal/server/migration.go`` 文件中修改``Start`` 方法：

```javascript
func (m *Migrate) Start(ctx context.Context) error {
	if err := m.db.AutoMigrate(&model.User{}); err != nil {
		m.log.Error("user migrate error", zap.Error(err))
		return err
	}
	if err := m.db.AutoMigrate(&model.Role{}); err != nil {
		m.log.Error("role migrate error", zap.Error(err))
		return err
	}
	if err := m.db.AutoMigrate(&model.Device{}); err != nil {
		m.log.Error("role migrate error", zap.Error(err))
		return err
	}
	m.log.Info("AutoMigrate success")
	os.Exit(0)
	return nil
}
```

然后在``/cmd/migration``目录执行``nunu run`` 命令。

虽然这种做法实现了所述问题，但是对代码入侵比较大，有没有什么自动的方式来实现此功能？

**Comment by codingcn** [comment]
```
if err := m.db.AutoMigrate(
		model.User{},
		model.Role{},
		model.Device{},
	); err != nil {
		m.log.Error("migrate error", zap.Error(err))
		return
	}
```

**Comment by lorenzohee** [comment]
有没有自动扫描model包下面的struct然后执行automigrate的方法？
或者在使用命令``nunu create model``的时候生成一个文件，然后在migration.go文件里面读取这个文件，然后生成数据库表？

**Comment by lorenzohee** [comment]
@codingcn

**Comment by lorenzohee** [comment]
> ```
> if err := m.db.AutoMigrate(
> 	model.User{},
> 	model.Role{},
> 	model.Device{},
> ); err != nil {
> 	m.log.Error("migrate error", zap.Error(err))
> 	return
> }
> ```

其实这个还是对代码有入侵

**Comment by codingcn** [comment]
不是太理解你指的侵入性是什么哈。通常数据表结构更新操作都需要非常谨慎，所以完全自动没有多大必要，而且golang是编译型语言，很多时候可能没有脚本语言那么便捷。
