### ISSUE TITLE
新版的接口错误处理问题

### ISSUE THREAD

**Issue by mozhiyun** [go-nunu/nunu#37]
`func HandleError(ctx *gin.Context, httpCode int, err error, data interface{}) {
	if data == nil {
		data = map[string]string{}
	}
	resp := Response{Code: ErrorCodeMap[err], Message: err.Error(), Data: data}
	ctx.JSON(httpCode, resp)
}`
这里这个code，如果在service层里的错误是未定义的会返回0吧，虽然外层已经有http错误码区分，但是0还是和success有所冲突吧，
而且Message是否应该把这种未知错误统一返回内部错误，在api里隐藏具体的错误信息呢，只在日志里记录是否会比较好

**Comment by codingcn** [comment]
的确有问题，感谢指正，晚点我更新下代码。
