### ISSUE TITLE
Question: What for REDIS?

### ISSUE THREAD

**Issue by remotejob** [go-nunu/nunu#38]
How redis is used in the project. It looks like it is not used at all?

**Comment by codingcn** [comment]
The usage of redis is very similar to MySQL, you only need to manipulate redis in the repo, and handle the business logic interface in the service, the code is similar to this

```
func (r *userRepository) BindTicket(ctx context.Context, ticket, openId string) error {
	return r.rdb.Set(ctx, fmt.Sprintf("Wx:Qrcode:%s", ticket), openId, time.Minute*30).Err()
}
```

**Comment by remotejob** [comment]
Thanks! I understand.
