### ISSUE TITLE
日志用起来感觉有些繁琐

### ISSUE THREAD

**Issue by youtiaoguagua** [go-nunu/nunu#39]
建议提供全局的日志，如果我需要在工具类里打印日志要么不用次整合包的统一日志，要么手动传递，有点太繁琐

**Comment by codingcn** [comment]
有需求的话，可以自己在log包定义一个全局变量，NewLog时进行赋值即可

**Comment by youtiaoguagua** [comment]
我的想法是把引用传递的log全部干掉，保留全局的即可，只是个想法哈
