### ISSUE TITLE
好奇new(handler、service等)的struct都改成了interface，是基于什么考虑和想法呢

### ISSUE THREAD

**Issue by longjianxin** [go-nunu/nunu#5]
如题，谢谢

**Comment by codingcn** [comment]
面向接口编程是一种灵活、可扩展、可维护的编程方式，可以提高代码的可测试性、可复用性和可扩展性。



https://github.com/go-nunu/nunu/blob/main/docs/zh/unit_testing.md#%E9%9D%A2%E5%90%91%E6%8E%A5%E5%8F%A3%E7%BC%96%E7%A8%8B
