### ISSUE TITLE
feat: 添加更多的部署方式

### ISSUE THREAD

**Issue by 0x0034** [go-nunu/nunu#52]
现在deploy 里面只有 `build` 和`docker-compose` , 是否还需要添加一下 `helm chart` 这种方式.

**Comment by codingcn** [comment]
服务这种，很少有公司会定义成helm chart吧。

**Comment by 0x0034** [comment]
只是一个标准部署的方式 , 像我们就是纯 on k8s . 说白了就是提供一种部署的途径罢了

**Comment by codingcn** [comment]
可以PR

**Comment by 0x0034** [comment]
得嘞. 有空 PR 一个上去
