### ISSUE TITLE
需要一个demo的使用指导

### ISSUE THREAD

**Issue by Hopetree** [go-nunu/nunu#53]
我研究了一下这个脚手架，发现根本不知道怎么用，文档指引是站在很熟悉框架的角度写的，只指导了一个项目怎么启动起来，但是没有给出指引我要怎么加入自己的东西，比如我想加入一个模型，应该做什么？我试了按照user的方式加入了一个新模型，但是搞了半天不知道怎么更新数据库的表。然后同理，怎么添加接口。。。
希望知道文档能够提供一个demo来说明这些步骤

**Comment by codingcn** [comment]
看下这个，https://github.com/go-nunu/nunu/blob/main/docs/zh/tutorial.md
