### ISSUE TITLE
[feat] 希望 model 生成可以内置基于 gorm gen

### ISSUE THREAD

**Issue by hh-Ink** [go-nunu/nunu#56]
[feat] 希望 model 生成可以内置基于 gorm gen

[https://gorm.io/zh_CN/gen/](https://gorm.io/zh_CN/gen/)

**Comment by codingcn** [comment]
这个比较简单，用户自己接入即可。而且大部分人可能都不需要gorm gen，nunu layout保持精简比较好

**Comment by hh-Ink** [comment]
在使用中的一些不方便

1. nunu 生成model 没要找到表结构转为结构体的方法。在实际开发过程中这一步很耗时
2.  gen  生成的文件名和 nunu 生成的规则不一致（这表名为 ‘xx_xx’ 时）。无法覆盖nunu生成的model文件，每次需要手动把gen生成的结构体粘贴到nunu 生成的model

希望处理的方式
nunu 生成 model 可以同时生成表结构对应的 结构体

**Comment by codingcn** [comment]
两者选其一，如果想自动化生成model结构，可以完全丢弃`nunu create model`，只需要依照gen的规则即可，golang中的文件名不会影响包的导入哈

**Comment by hh-Ink** [comment]
好的  谢谢
