### ISSUE TITLE
undefined: newApp

### ISSUE THREAD

**Issue by stuchilde** [go-nunu/nunu#6]
➜  k8s_deploy git:(main) ✗ go build cmd/server/main.go       
# command-line-arguments
cmd/server/main.go:15:23: undefined: newApp

go build error

**Comment by stuchilde** [comment]
now, it's ok. i just add log. maybe before it's a cache.

**Comment by codingcn** [comment]
```
go build cmd/server/main.go cmd/server/wire.go
```
