### ISSUE TITLE
请问mac电脑，运行/projectName/deploy/build/Dockerfile的脚本打镜像，老是报 COPY failed: forbidden path outside the build context: .. ()

### ISSUE THREAD

**Issue by drama10096** [go-nunu/nunu#60]
zj@MacdeMacBook-Pro build % pwd
/Users/zj/go/src/projectName/deploy/build
zj@MacdeMacBook-Pro build % docker build -t  1.1.1.1:5000/demo-api:v1 --build-arg APP_CONF=config/prod.yml --build-arg  APP_RELATIVE_PATH=./cmd/server/...  .
Sending build context to Docker daemon   2.56kB
Step 1/18 : ARG REGISTRY=docker.io
Step 2/18 : FROM ${REGISTRY}/golang:1.18-alpine3.16 AS builder
 ---> b60e0f1fb4d1
Step 3/18 : RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
 ---> Using cache
 ---> 0799ab4dbe64
Step 4/18 : ARG APP_RELATIVE_PATH
 ---> Using cache
 ---> 22483ea929fb
Step 5/18 : COPY .. /data/app
COPY failed: forbidden path outside the build context: .. ()
zj@MacdeMacBook-Pro build %

**Comment by codingcn** [comment]
修改下`deploy/build/Dockerfile`里面的go镜像版本号

`FROM ${REGISTRY}/golang:1.19-alpine AS builder`

可以参考makefile
```
cd projectName

make docker
```

**Comment by drama10096** [comment]
好的，感谢指导回复

**Comment by drama10096** [comment]
![Uploading Snipaste_2024-06-04_10-14-56.png…]()

**Comment by drama10096** [comment]
RUN rm -rf /data/app/bin/
RUN export GOPROXY=https://goproxy.cn,direct && go mod tidy && go build -ldflags="-s -w" -o ./bin/server ${APP_RELATIVE_PATH}
RUN mv config /data/app/bin/


#docker build -t  1.1.1.1:5000/demo-api:v1 --build-arg APP_CONF=config/prod.yml --build-arg  APP_RELATIVE_PATH=./cmd/server/...  .

以上内容里的“ ./bin/server ”  和   ./cmd/server/ 是不是不太对应？？？？
感觉“构建镜像目录”，也有可能没对应上

**Comment by codingcn** [comment]
通常来说，一个镜像里面只会有一个服务，所以不管是`./cmd/server`还是`./cmd/task`或者是`./cmd/xxxxxx`，我们在镜像里面都可以编译为一个固定的编译结果`./bin/server`，这是不会冲突的，而且还有些其它好处。

但如果我们不使用docker的话，那么还是使用`./bin/server`、`./bin/task`、`./bin/xxxxxx`比较好，避免文件冲突。

**Comment by drama10096** [comment]
哦哦 好的好的，回去我试试，我以为 “COPY failed: forbidden path outside the build context: .. () ”，是目录拷贝方面的原因呢

**Comment by drama10096** [comment]
#docker build -t  1.1.1.1:5000/demo-api:v1 --build-arg APP_CONF=config/prod.yml --build-arg  APP_RELATIVE_PATH=./cmd/server/...  .
#docker run -it --rm --entrypoint=ash 1.1.1.1:5000/demo-api:v1  

/xxx/deploy/build/Dockerfile 里这个最后面的备注，到底在哪里执行的？？？  还是报 COPY failed: forbidden path outside the build context: .. ()

**Comment by drama10096** [comment]
/xxx/deploy/build/Dockerfile   这个是有用的么？？？？

**Comment by drama10096** [comment]
zj@MacdeMacBook-Pro test_nunu_01 % make docker
docker build -f deploy/build/Dockerfile --build-arg APP_RELATIVE_PATH=./cmd/task -t 1.1.1.1:5000/demo-task:v1 .
Sending build context to Docker daemon  257.5kB
Step 1/18 : ARG REGISTRY=docker.io
Step 2/18 : FROM ${REGISTRY}/golang:1.19-alpine AS builder
 ---> 5da886f1a5e7
Step 3/18 : RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
 ---> Using cache
 ---> 700f4db286fc
Step 4/18 : ARG APP_RELATIVE_PATH
 ---> Using cache
 ---> fd477c129b84
Step 5/18 : COPY .. /data/app
COPY failed: forbidden path outside the build context: .. ()
make: *** [docker] Error 1
zj@MacdeMacBook-Pro test_nunu_01 % 



执行make docker 也报以上错误， 这个情况是环境有问题么？？？  感觉mac电脑上无法打镜像包

**Comment by drama10096** [comment]
zj@MacdeMacBook-Pro test_nunu_01 % go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zj/Library/Caches/go-build"
GOENV="/Users/zj/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zj/work_location/space_go/src/pkg/mod"
GONOPROXY="gitlab.com"
GONOSUMDB="gitlab.com"
GOOS="darwin"
GOPATH="/Users/zj/work_location/space_go/src:/Users/zj/go/src"
GOPRIVATE="gitlab.com"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/zj/go/go1.19.2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/zj/go/go1.19.2/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/zj/work_location/space_go/src/test_nunu_01/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b0/9nmv33cn3439jfhydkyl2s280000gp/T/go-build1396359952=/tmp/go-build -gno-record-gcc-switches -fno-common"
zj@MacdeMacBook-Pro test_nunu_01 % 


以上是我的本地环境，test_nunu_01 是我新创建的，我的电脑是mac电脑 inter 芯片的

**Comment by drama10096** [comment]
解决了 Docker Engine 的配置原因，  "features": {"buildkit": true},  这里面的buildkit得用true（之前我用的false）
