### ISSUE TITLE
关于Repository 设计上的一些困惑

### ISSUE THREAD

**Issue by ming200825** [go-nunu/nunu#62]
### 2. 如更新密码 ,更新用户余额, 更新用户昵称 这类的 是否也是各定义新方法  还是说只用一个
    Update(ctx context.Context, user *model.User) error  来处理,  

### 3 ,在查询后 要并发事务锁 在 Repository中 GetBy 需要锁记录时(如下单后扣余额) 怎么处理更好

**Comment by codingcn** [comment]
觉得怎么方便怎么来，事务相关建议再service里面处理
