### ISSUE TITLE
执行nunu wire all执行失败，必须修改handler文件为接口实现才会成功

### ISSUE THREAD

**Issue by wilsonp** [go-nunu/nunu#68]
根据https://github.com/go-nunu/nunu/blob/main/docs/zh/tutorial.md指南
1.选择简化版模板生成了项目
2.删除wire_gen.go,重新执行nunu wire all，执行成功，生成了wire_gen.go
3.执行nunu create all user_lesson,正常创建了handler,service,repository,modle的go文件
4.修改http.go,增加handler
5.修改wire.go,增加NewUserLessonService ,NewUserLessonHandler,NewUserLessonRepository
6.执行nunu wire all，执行失败：inject NewWire: no provider found for nunu-test/internal/handler.UserLessonHandler

7.修改生成的handler下user_lesson.go文件
参考项目中的handler下的user.go的结构，发现user.go中是实现了接口的
```
type UserHandler interface {
	GetUserById(ctx *gin.Context)
	UpdateUser(ctx *gin.Context)
}

type userHandler struct {
	*Handler
	userService service.UserService
}
```
同样增加接口实现：
```
type UserLessonHandler interface {
	GetUserLesson(ctx *gin.Context)
}

type userLessonHandler struct {
	*Handler
	userLessonService service.UserLessonService
}

func NewUserLessonHandler(
	handler *Handler,
	userLessonService service.UserLessonService,
) UserLessonHandler {
	return &userLessonHandler{
		Handler:           handler,
		userLessonService: userLessonService,
	}
}
```

再次执行nunu wire all的时候执行成功，所以是不是通过nunu create all创建的handler组件必须修改下，要通过接口实现才可以成功呢？

**Comment by codingcn** [comment]
handler可以不写interface，参考高级模板吧，基础模板没有及时移除interface
