### ISSUE TITLE
为什么api这个目录放的user 相关请求或者返回的结构体

### ISSUE THREAD

**Issue by codermama** [go-nunu/nunu#69]
为什么api这个目录放的user 相关请求或者返回的结构体

**Comment by codermama** [comment]
![Uploading WX20240817-180107@2x.png…]()

**Comment by codermama** [comment]
<img width="700" alt="image" src="https://github.com/user-attachments/assets/15a5930c-8719-46d6-a840-9dd6dfa82c36">

**Comment by codingcn** [comment]
参考这个，如果是proto的话，也可以放到api目录下

https://github.com/golang-standards/project-layout/tree/master/api

**Comment by codermama** [comment]
嗯 谢谢
