### ISSUE TITLE
关于框架内多个 type 注入的疑问

### ISSUE THREAD

**Issue by ToQuery** [go-nunu/nunu#70]
java 转 golang 码农 ，使用中发现，如果我创建了新对象的 handler model repository service等文件，那么就需要在 `cmd/server/wire/wire_gen.go` 文件中添加对应的 handler repository service ，并调整 `internal/server/http.go` 文件的 NewHTTPServer 入参。

对此有一些疑问：
1. 如果创建了多个对象都需要手动创建改参，有没有类似 spring 批量注入的机制，不需要修改自动注入
2. 与上一个问题类似，NewHTTPServer函数，如果接口很多，那入参参数是不是也很多，有什么优化可以处理？

**Comment by codingcn** [comment]
注入是自动的，禁止手动修改`wire/wire_gen.go`，只需要修改`wire/wire.go`就行，然后执行`nunu wire all` 

NewHTTPServer的入参是很多

**Comment by ToQuery** [comment]
嗯，但报错了，项目代码 https://github.com/ToQuery/example-nunu

wire.go path:  /xxx/cmd/server/wire/
wire fail: exit status 1
wire: /xxx/cmd/server/wire/wire.go:27:2: repository.AppRepository (type) is not an expression
wire: /xxx/cmd/server/wire/wire.go:41:2: handler.AppHandler (type) is not an expression
wire: generate failed
