### ISSUE TITLE
数据库读写分离，多redis的连接等是否有考虑加上呢？

### ISSUE THREAD

**Issue by llfire** [go-nunu/nunu#72]
对于高并发大流量应该是必要的功能不知道是有有考虑功能加入进去呢？

**Comment by codingcn** [comment]
读写分离查阅GORM的文档即可，跟nunu关联性不大
https://gorm.io/zh_CN/docs/dbresolver.html

多实例连接可以参考mysql的，几乎是一样的操作
https://github.com/go-nunu/nunu/issues/29
