### ISSUE TITLE
尝试了一下，质量挺高，赞 

### ISSUE THREAD

**Issue by nanzm** [go-nunu/nunu#8]
1. 希望能支持 国际化 
2. migration 要是能支持手写 sql 就好了

**Comment by yangyongzhen** [comment]
赞！功能不错！

**Comment by yangyongzhen** [comment]
我特意写了篇博客《go-Nunu，一个好用的脚手架推荐，助你快速构建Go应用》推荐了下：https://blog.csdn.net/yyz_1987/article/details/131548195

**Comment by codingcn** [comment]
国际化的话，目前主流的前后端分离开发方式，i18n通常是由客户端来处理。

而且国内大部分项目其实并没有国际化需求。服务端实现i18n的话也很简单，完全可以自己定制实现哈。


migration基于GORM实现，目前应该不支持原生SQL

https://gorm.io/zh_CN/docs/migration.html
